modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="pixelmonhafix"
version="1.0"
displayName="Pixelmon Quests Addon"
displayURL="https://github.com/CrushTheDragon" # URL HERE
credits="https://github.com/CrushTheDragon" # Your name here
authors="https://github.com/CrushTheDragon" # Your name here
description='''
Description of the mod here
'''

[[dependencies.pixelmonhafix]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pixelmonhafix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"


[[dependencies.pixelmonhafix]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.2,)"
    ordering="NONE"
    side="BOTH"